class RouteInfo {
  const RouteInfo({required this.route, required this.origin, required this.destination, required this.via, required this.pdf});

  final String route;
  final String origin;
  final String destination;
  final String via;
  final String pdf;
}

const List<RouteInfo> kJutcRoutes = [
  RouteInfo(route: '610', origin: 'Ocho Rios', destination: 'City', via: 'North-South Highway', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_610.pdf'),
  RouteInfo(route: '513', origin: 'May Pen', destination: 'City', via: 'East-West Highway, Six Miles', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_513.pdf'),
  RouteInfo(route: '20C', origin: 'Greater Portmore', destination: 'City', via: 'Portmore Toll, Three Miles', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_20C.pdf'),
  RouteInfo(route: '3C', origin: 'Christian Gardens', destination: 'City', via: 'Portmore Toll, Three Miles', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_3C.pdf'),
  RouteInfo(route: '19', origin: 'Greater Portmore', destination: 'Papine/UWI', via: 'Portmore Toll, HWT', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_19.pdf'),
  RouteInfo(route: '13', origin: 'Greater Portmore', destination: 'CMU', via: 'Marcus Garvey Drive', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_13.pdf'),
  RouteInfo(route: '27', origin: 'Kitson Town', destination: 'Spanish Town', via: "St. John's Road", pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_27.pdf'),
  RouteInfo(route: '620Ex', origin: 'Montego Bay', destination: 'Half Way Tree', via: 'North-South Highway', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_620Ex.pdf'),
  RouteInfo(route: '606Ex', origin: 'Linstead', destination: 'Downtown', via: 'North-South Highway', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_606Ex.pdf'),
  RouteInfo(route: '520Ex', origin: 'Negril', destination: 'Half Way Tree', via: 'South Coast', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_520Ex.pdf'),
  RouteInfo(route: '512', origin: 'Mandeville', destination: 'Downtown', via: 'East-West Highway', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_512.pdf'),
  RouteInfo(route: '509', origin: 'Longville Park', destination: 'Spanish Town', via: 'Old Harbour, Gutters', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_509.pdf'),
  RouteInfo(route: '508', origin: 'Old Harbour', destination: 'UWI Front Gate', via: 'Gutters, McCooks Pen', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_508.pdf'),
  RouteInfo(route: '605', origin: 'Linstead', destination: 'Spanish Town', via: 'Bog Walk, Angels', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_605.pdf'),
  RouteInfo(route: '504', origin: 'Chapelton', destination: 'May Pen', via: 'Turners, New Longsville', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_504.pdf'),
  RouteInfo(route: '52B', origin: 'Grande Hole', destination: 'Half Way Tree', via: 'Castleton, Stony Hill', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_52B.pdf'),
  RouteInfo(route: '311', origin: 'Catherine Est.', destination: 'Cross Roads', via: 'Braeton Road, Toll', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/PREMIUM_SCHEDULE.pdf'),
  RouteInfo(route: '9', origin: 'Naggo Head', destination: 'Spanish Town', via: 'Braeton Parkway', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_9.pdf'),
  RouteInfo(route: '310', origin: 'Phoenix Park 1', destination: 'Cross Roads', via: 'Braeton Road, Toll', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/PREMIUM_SCHEDULE.pdf'),
  RouteInfo(route: '309', origin: 'Phoenix Park 2', destination: 'Cross Roads', via: 'Braeton Road, Toll', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/PREMIUM_SCHEDULE.pdf'),
  RouteInfo(route: '135', origin: 'Silver Sun Est.', destination: 'City', via: 'Spanish Town Toll', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/PREMIUM_SCHEDULE.pdf'),
  RouteInfo(route: '501', origin: 'Old Harbour', destination: 'May Pen', via: 'Free Town', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_501.pdf'),
  RouteInfo(route: '502', origin: 'Lionel Town', destination: 'May Pen', via: 'Vere, Hayes', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_502.pdf'),
  RouteInfo(route: '511', origin: 'May Pen', destination: 'Spanish Town', via: 'East-West Highway', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_511.pdf'),
  RouteInfo(route: '510', origin: 'Old Harbour', destination: 'Spanish Town', via: 'Church Pen', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_510.pdf'),
  RouteInfo(route: '702', origin: 'Morant Bay', destination: 'City', via: 'Yallahs, Bull Bay', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_702.pdf'),
  RouteInfo(route: '701', origin: 'Yallahs', destination: 'City', via: 'Albion, Bull Bay', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_701.pdf'),
  RouteInfo(route: '19Bx', origin: 'Grt. Portmore', destination: 'Papine', via: 'Braeton Pkwy, Toll', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_19Bx.pdf'),
  RouteInfo(route: '503', origin: 'Toll Gate', destination: 'May Pen', via: 'Osbourne Store', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_503.pdf'),
  RouteInfo(route: '137', origin: 'Silver Sun Est.', destination: 'New Kingston', via: 'Spanish Town Toll', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/PREMIUM_SCHEDULE.pdf'),
  RouteInfo(route: '19Ax', origin: 'Grt. Portmore', destination: 'Papine', via: 'Hellshire Rd, Toll', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_19Ax.pdf'),
  RouteInfo(route: '136', origin: 'New Hbr Vill 4', destination: 'Cross Roads', via: 'Washington Blvd', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/PREMIUM_SCHEDULE.pdf'),
  RouteInfo(route: '53Ex', origin: 'Above Rocks', destination: 'City', via: 'Stony Hill', pdf: 'https://www.google.com/search?q=https://jutc.gov.jm/bus-route-info/timetables/Schedule_53Ex.pdf&authuser=2'),
  RouteInfo(route: '83B', origin: 'Half Way Tree', destination: 'Mountain View', via: 'New Kingston', pdf: 'https://www.google.com/search?q=https://jutc.gov.jm/bus-route-info/timetables/Schedule_83B.pdf&authuser=2'),
  RouteInfo(route: '320', origin: 'Grt. Portmore', destination: 'Cross Roads', via: 'Braeton Pkwy, Toll', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/PREMIUM_SCHEDULE.pdf'),
  RouteInfo(route: '319', origin: 'Grt. Portmore', destination: 'Papine', via: 'Hellshire Rd, Toll', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/PREMIUM_SCHEDULE.pdf'),
  RouteInfo(route: '318', origin: 'Grt. Portmore', destination: 'Cross Roads', via: 'Braeton Pkwy, HWT', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/PREMIUM_SCHEDULE.pdf'),
  RouteInfo(route: '317', origin: 'Grt. Portmore', destination: 'Cross Roads', via: 'Hellshire Rd, Toll', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/PREMIUM_SCHEDULE.pdf'),
  RouteInfo(route: '316', origin: 'Grt. Portmore', destination: 'Cross Roads', via: 'Hellshire Rd, Mandela', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/PREMIUM_SCHEDULE.pdf'),
  RouteInfo(route: '315', origin: 'Grt. Portmore', destination: 'City', via: 'Braeton Pkwy, Toll', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/PREMIUM_SCHEDULE.pdf'),
  RouteInfo(route: '314', origin: 'Cumberland', destination: 'New Kingston', via: 'Portmore Toll', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/PREMIUM_SCHEDULE.pdf'),
  RouteInfo(route: '312', origin: 'Cumberland', destination: 'Cross Roads', via: 'Toll, Hagley Park', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/PREMIUM_SCHEDULE.pdf'),
  RouteInfo(route: '308', origin: 'Naggo Head', destination: 'Papine', via: 'Toll, Hope Road', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/PREMIUM_SCHEDULE.pdf'),
  RouteInfo(route: '303', origin: 'Christian Gdns', destination: 'Papine', via: 'Waterford, Toll', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/PREMIUM_SCHEDULE.pdf'),
  RouteInfo(route: '301', origin: 'Hellshire', destination: 'Cross Roads', via: 'Hellshire Rd, Toll', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/PREMIUM_SCHEDULE.pdf'),
  RouteInfo(route: '295', origin: 'Harbour View', destination: 'Half Way Tree', via: 'Mountain View', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/PREMIUM_SCHEDULE.pdf'),
  RouteInfo(route: '134', origin: 'The Vineyards', destination: 'City', via: 'Washington Blvd', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/PREMIUM_SCHEDULE.pdf'),
  RouteInfo(route: '133', origin: 'Claremount', destination: 'City', via: 'Vineyards Toll', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/PREMIUM_SCHEDULE.pdf'),
  RouteInfo(route: '132', origin: 'New Hbr Vill', destination: 'Cross Roads', via: 'Vineyards Toll', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/PREMIUM_SCHEDULE.pdf'),
  RouteInfo(route: '131', origin: 'New Hbr Vill', destination: 'Cross Roads', via: 'Vineyards Toll', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/PREMIUM_SCHEDULE.pdf'),
  RouteInfo(route: '130', origin: 'Longville', destination: 'City', via: 'Molynes Road', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/PREMIUM_SCHEDULE.pdf'),
  RouteInfo(route: '129', origin: 'Eltham/Angels', destination: 'City', via: 'Molynes Road', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/PREMIUM_SCHEDULE.pdf'),
  RouteInfo(route: '128', origin: 'Angels', destination: 'Papine', via: 'Washington Blvd', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/PREMIUM_SCHEDULE.pdf'),
  RouteInfo(route: '127', origin: 'Angels', destination: 'Cross Roads', via: 'Washington Blvd', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/PREMIUM_SCHEDULE.pdf'),
  RouteInfo(route: '126', origin: 'White Waters', destination: 'Cross Roads', via: 'Washington Blvd', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/PREMIUM_SCHEDULE.pdf'),
  RouteInfo(route: '125', origin: 'Green Acres', destination: 'Cross Roads', via: 'Washington Blvd', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/PREMIUM_SCHEDULE.pdf'),
  RouteInfo(route: '124', origin: 'Ebony Vale', destination: 'City', via: 'Molynes Road', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/PREMIUM_SCHEDULE.pdf'),
  RouteInfo(route: '123', origin: 'Ensom Acres', destination: 'Cross Roads', via: 'Washington Blvd', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/PREMIUM_SCHEDULE.pdf'),
  RouteInfo(route: '122', origin: 'St Johns Hts', destination: 'Cross Roads', via: 'Washington Blvd', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/PREMIUM_SCHEDULE.pdf'),
  RouteInfo(route: '121', origin: 'Inswood Vill', destination: 'City', via: 'Washington Blvd', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/PREMIUM_SCHEDULE.pdf'),
  RouteInfo(route: '103', origin: 'Spanish Town', destination: 'Cross Roads', via: 'Washington Blvd', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/PREMIUM_SCHEDULE.pdf'),
  RouteInfo(route: '102', origin: 'Harbour View', destination: 'August Town', via: 'East St, HWT', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/PREMIUM_SCHEDULE.pdf'),
  RouteInfo(route: '101', origin: 'Grt. Portmore', destination: 'Constant Spr.', via: 'Braeton Rd, Mandela', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/PREMIUM_SCHEDULE.pdf'),
  RouteInfo(route: '99Ex', origin: 'Harbour View', destination: 'City', via: 'Sir Florizel Glaspole', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_99Ex.pdf'),
  RouteInfo(route: '97Ex', origin: 'Bull Bay', destination: 'City', via: 'Sir Florizel Glaspole', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_97Ex.pdf'),
  RouteInfo(route: '95Ex', origin: 'Bull Bay', destination: 'UWI Back Gate', via: 'Mountain View', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_95Ex.pdf'),
  RouteInfo(route: '78Ex', origin: 'August Town', destination: 'City', via: 'Papine, Cross Roads', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_78Ex.pdf'),
  RouteInfo(route: '75Ex', origin: 'Ferry', destination: 'UWI Back Gate', via: 'Molynes Rd, HWT', pdf: 'https://www.google.com/search?q=https://jutc.gov.jm/bus-route-info/timetables/Schedule_75Ex.pdf&authuser=2'),
  RouteInfo(route: '75Ax', origin: 'Ferry', destination: 'UWI Back Gate', via: 'Dunrobin Ave', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_75Ax.pdf'),
  RouteInfo(route: '73Ax', origin: 'HWT', destination: 'UWI Back Gate', via: 'Hope Road', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_73Ax.pdf'),
  RouteInfo(route: '54Ex', origin: 'Border', destination: 'City', via: 'Lawrence Tavern', pdf: 'https://www.google.com/search?q=https://jutc.gov.jm/bus-route-info/timetables/Schedule_54Ex.pdf&authuser=2'),
  RouteInfo(route: '51Ex', origin: 'Three Miles', destination: 'Papine', via: 'Hagley Park Rd', pdf: 'https://www.google.com/search?q=https://jutc.gov.jm/bus-route-info/timetables/Schedule_51Ex.pdf&authuser=2'),
  RouteInfo(route: '50Ex', origin: 'Seaview', destination: 'Papine', via: 'Hagley Park Rd', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_50Ex.pdf'),
  RouteInfo(route: '45Ex', origin: 'Grt House Cir', destination: 'UWI Back Gate', via: 'Meadowbrook', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_45Ex.pdf'),
  RouteInfo(route: '32Ex', origin: 'Duhaney Park', destination: 'Cross Roads', via: 'Washington Blvd', pdf: 'https://www.google.com/search?q=https://jutc.gov.jm/bus-route-info/timetables/Schedule_32Ex.pdf&authuser=2'),
  RouteInfo(route: '32Ax', origin: 'Duhaney Park', destination: 'Cross Roads', via: 'Duhaney Park', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_32Ax.pdf'),
  RouteInfo(route: '25Ex', origin: 'Spanish Town', destination: 'Constant Spr.', via: 'Washington Blvd', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_25Ex.pdf'),
  RouteInfo(route: '24Ex', origin: 'Spanish Town', destination: 'UWI Back Gate', via: 'Washington Blvd', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_24Ex.pdf'),
  RouteInfo(route: '22Ex', origin: 'Spanish Town', destination: 'City', via: 'Dyke Road', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_22Ex.pdf'),
  RouteInfo(route: '22Bx', origin: 'Spanish Town', destination: 'Cross Roads', via: 'Dyke Road', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_22Bx.pdf'),
  RouteInfo(route: '21Ax', origin: 'Spanish Town', destination: 'Cross Roads', via: 'Washington Blvd', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_21Ax.pdf'),
  RouteInfo(route: '20Ax', origin: 'Grt. Portmore', destination: 'New Kingston', via: 'Braeton, Toll', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_20Ax.pdf'),
  RouteInfo(route: '17Ex', origin: 'Grt. Portmore', destination: 'Cross Roads', via: 'Hellshire Rd, Toll', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_17Ex.pdf'),
  RouteInfo(route: '17Ax', origin: 'Grt. Portmore', destination: 'New Kingston', via: 'Hellshire Rd, Toll', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_17Ax.pdf'),
  RouteInfo(route: '16Bx', origin: 'Grt. Portmore', destination: 'Constant Spr.', via: 'Hellshire Rd', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_16Bx.pdf'),
  RouteInfo(route: '12Ax', origin: 'Naggo Head', destination: 'New Kingston', via: 'Cumberland, Toll', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_12Ax.pdf'),
  RouteInfo(route: '8Ax', origin: 'Naggo Head', destination: 'New Kingston', via: 'Garveymeade, Toll', pdf: 'https://www.google.com/search?q=https://jutc.gov.jm/bus-route-info/timetables/Schedule_8Ax.pdf&authuser=2'),
  RouteInfo(route: '3Ax', origin: 'Christian Gdns', destination: 'New Kingston', via: 'Passagefort, Toll', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_3Ax.pdf'),
  RouteInfo(route: '900', origin: 'Half Way Tree', destination: 'Papine', via: 'Hope Road', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_900.pdf'),
  RouteInfo(route: '800', origin: 'Half Way Tree', destination: 'Cross Roads', via: 'New Kingston', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_800.pdf'),
  RouteInfo(route: '99', origin: 'Harbour View', destination: 'City', via: 'Sir Florizel Glaspole', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_99.pdf'),
  RouteInfo(route: '98', origin: 'Port Royal', destination: 'City', via: 'Sir Florizel Glaspole', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_98.pdf'),
  RouteInfo(route: '97', origin: 'Bull Bay', destination: 'City', via: 'Sir Florizel Glaspole', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_97.pdf'),
  RouteInfo(route: '89', origin: 'Vineyard Town', destination: 'City', via: 'Deanery Road', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_89.pdf'),
  RouteInfo(route: '88', origin: 'Cross Roads', destination: 'City', via: 'Mountain View', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_88.pdf'),
  RouteInfo(route: '86', origin: 'Cross Roads', destination: 'City', via: 'South Camp Road', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_86.pdf'),
  RouteInfo(route: '83', origin: 'Half Way Tree', destination: 'City', via: 'Mountain View', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_83.pdf'),
  RouteInfo(route: '78', origin: 'August Town', destination: 'City', via: 'Papine, Cross Roads', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_78.pdf'),
  RouteInfo(route: '77', origin: 'August Town', destination: 'City', via: 'Mountain View', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_77.pdf'),
  RouteInfo(route: '76', origin: 'Barbican', destination: 'City', via: 'East Kings House', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_76.pdf'),
  RouteInfo(route: '75A', origin: 'Ferry', destination: 'UWI Back Gate', via: 'Dunrobin Avenue', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_75A.pdf'),
  RouteInfo(route: '75', origin: 'Ferry', destination: 'Papine', via: 'Molynes Road', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_75.pdf'),
  RouteInfo(route: '74', origin: 'Barbican', destination: 'City', via: 'Old Church Road', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_74.pdf'),
  RouteInfo(route: '72', origin: 'August Town', destination: 'Half Way Tree', via: 'Mona Road', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_72.pdf'),
  RouteInfo(route: '68', origin: 'UWI Back Gate', destination: 'City', via: 'Hope Pastures', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_68.pdf'),
  RouteInfo(route: '66', origin: 'Hermitage', destination: 'City', via: 'Mona Road', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_66.pdf'),
  RouteInfo(route: '16B', origin: 'Grt. Portmore', destination: 'Constant Spr.', via: 'Hellshire Rd', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_16B.pdf'),
  RouteInfo(route: '61', origin: 'Gordon Town', destination: 'City', via: 'Old Hope Road', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_61.pdf'),
  RouteInfo(route: '54', origin: 'Border', destination: 'Half Way Tree', via: 'Stony Hill', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_54.pdf'),
  RouteInfo(route: '53', origin: 'Above Rocks', destination: 'Half Way Tree', via: 'Stony Hill', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_53.pdf'),
  RouteInfo(route: '52A', origin: 'Temple Hall', destination: 'City', via: 'Stony Hill', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_52A.pdf'),
  RouteInfo(route: '50B', origin: 'Seaview', destination: 'City', via: 'Three Miles', pdf: 'https://www.google.com/search?q=https://jutc.gov.jm/bus-route-info/timetables/Schedule_50B.pdf&authuser=2'),
  RouteInfo(route: '50A', origin: 'Seaview', destination: 'City', via: 'Three Miles', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_50A.pdf'),
  RouteInfo(route: '50', origin: 'Seaview', destination: 'Half Way Tree', via: 'Hagley Park Road', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_50.pdf'),
  RouteInfo(route: '49', origin: 'Norbrook', destination: 'City', via: 'Shortwood Road', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_49.pdf'),
  RouteInfo(route: '47', origin: 'Chancery St', destination: 'City', via: 'Molynes Road', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_47.pdf'),
  RouteInfo(route: '46B', origin: 'Grt House Cir', destination: 'Half Way Tree', via: 'Meadowbrook', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_46B.pdf'),
  RouteInfo(route: '46', origin: 'Grt House Cir', destination: 'City', via: 'Meadowbrook', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_46.pdf'),
  RouteInfo(route: '44B', origin: 'Grt House Cir', destination: 'Half Way Tree', via: 'Havendale', pdf: 'https://www.google.com/search?q=https://jutc.gov.jm/bus-route-info/timetables/Schedule_44B.pdf&authuser=2'),
  RouteInfo(route: '44', origin: 'Grt House Cir', destination: 'City', via: 'Havendale', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_44.pdf'),
  RouteInfo(route: '32B', origin: 'Duhaney Park', destination: 'HWT', via: 'Washington Blvd', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_32B.pdf'),
  RouteInfo(route: '32', origin: 'Cooreville', destination: 'City', via: 'Duhaney Park', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_32.pdf'),
  RouteInfo(route: '31A', origin: 'Chancery St', destination: 'City', via: 'Weymouth Dr', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_31A.pdf'),
  RouteInfo(route: '31', origin: 'Chancery St', destination: 'City', via: 'Weymouth Dr', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_31.pdf'),
  RouteInfo(route: '30', origin: 'Chancery St', destination: 'City', via: 'Pembroke Hall', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_30.pdf'),
  RouteInfo(route: '26', origin: 'Spanish Town', destination: 'Half Way Tree', via: 'Hagley Park Road', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_26.pdf'),
  RouteInfo(route: '23A', origin: 'Spanish Town', destination: 'Half Way Tree', via: 'Washington Blvd', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_23A.pdf'),
  RouteInfo(route: '22A', origin: 'Spanish Town', destination: 'City', via: 'Marcus Garvey Dr', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_22A.pdf'),
  RouteInfo(route: '22', origin: 'Spanish Town', destination: 'City', via: 'Spanish Town Road', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_22.pdf'),
  RouteInfo(route: '21B', origin: 'Spanish Town', destination: 'Cross Roads', via: 'Washington Blvd', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_21B.pdf'),
  RouteInfo(route: '21', origin: 'Spanish Town', destination: 'Half Way Tree', via: 'Washington Blvd', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_21.pdf'),
  RouteInfo(route: '20A', origin: 'Grt. Portmore', destination: 'Half Way Tree', via: 'Braeton Pkwy, Toll', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_20A.pdf'),
  RouteInfo(route: '20', origin: 'Grt. Portmore', destination: 'City', via: 'Braeton Pkwy, Toll', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_20.pdf'),
  RouteInfo(route: '18A', origin: 'Grt. Portmore', destination: 'Half Way Tree', via: 'Braeton Rd, Toll', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_18A.pdf'),
  RouteInfo(route: '18', origin: 'Grt. Portmore', destination: 'City', via: 'Braeton Rd, Toll', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_18.pdf'),
  RouteInfo(route: '17A', origin: 'Grt. Portmore', destination: 'Half Way Tree', via: 'Hellshire Rd, Toll', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_17A.pdf'),
  RouteInfo(route: '17', origin: 'Grt. Portmore', destination: 'City', via: 'Hellshire Rd, Toll', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_17.pdf'),
  RouteInfo(route: '16A', origin: 'Grt. Portmore', destination: 'Cross Roads', via: 'Braeton, Mandela', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_16A.pdf'),
  RouteInfo(route: '16', origin: 'Grt. Portmore', destination: 'Cross Roads', via: 'Braeton Pkwy, Toll', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_16.pdf'),
  RouteInfo(route: '15A', origin: 'Grt. Portmore', destination: 'Cross Roads', via: 'Braeton, Mandela', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_15A.pdf'),
  RouteInfo(route: '12A', origin: 'Naggo Head', destination: 'Half Way Tree', via: 'Cumberland, Toll', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_12A.pdf'),
  RouteInfo(route: '12', origin: 'Naggo Head', destination: 'City', via: 'Cumberland, Toll', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_12.pdf'),
  RouteInfo(route: '8A', origin: 'Naggo Head', destination: 'Half Way Tree', via: 'Garveymeade, Toll', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_8A.pdf'),
  RouteInfo(route: '8', origin: 'Naggo Head', destination: 'City', via: 'Garveymeade, Toll', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_8.pdf'),
  RouteInfo(route: '6', origin: 'Grt. Portmore', destination: 'Spanish Town', via: 'Naggo Head, Mandela', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_6.pdf'),
  RouteInfo(route: '5A', origin: 'Caribbean Est', destination: 'Half Way Tree', via: 'Passagefort, Toll', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_5A.pdf'),
  RouteInfo(route: '5', origin: 'Caribbean Est', destination: 'City', via: 'Passagefort, Toll', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_5.pdf'),
  RouteInfo(route: '4', origin: 'Christian Gdns', destination: 'Cross Roads', via: 'Passagefort, Toll', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_4.pdf'),
  RouteInfo(route: '3A', origin: 'Christian Gdns', destination: 'Half Way Tree', via: 'Passagefort, Toll', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_3A.pdf'),
  RouteInfo(route: '3', origin: 'Christian Gdns', destination: 'City', via: 'Passagefort, Toll', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_3.pdf'),
  RouteInfo(route: '1A', origin: 'Hellshire', destination: 'Half Way Tree', via: 'Naggo Head, Toll', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_1A.pdf'),
  RouteInfo(route: '1', origin: 'Hellshire', destination: 'City', via: 'Naggo Head, Toll', pdf: 'https://jutc.gov.jm/bus-route-info/timetables/Schedule_1.pdf'),
];
